# These two values are generated by Snowflake when the storage
# integration is created. The root module uses them to connect
# the IAM role trust policy so Snowflake can actually assume
# the role and read from S3.

output "storage_aws_iam_user_arn" {
  description = "Snowflake IAM user ARN — goes into IAM trust policy principal"
  value       = snowflake_storage_integration.s3.storage_aws_iam_user_arn
}

output "storage_aws_external_id" {
  description = "Snowflake external ID — goes into IAM trust policy condition"
  value       = snowflake_storage_integration.s3.storage_aws_external_id
}